Мой первый пулреквест, ура!
chandrey34/BreakingBadInfo pull request #1
Opened 2022-04-28 18:16 UTC by chandrey34

Сделал 4 кнопки, и переходы в каждую кнопку, в кнопке Серия сделал 5 кнопок с названиями сезонов.

2022-04-29 10:16 UTC, AlexeyGvozdev commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-fragment:2.3.5'
Зачем это? Где используешь?

2022-04-29 10:16 UTC, AlexeyGvozdev commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
Почему exported = false?

2022-04-29 10:16 UTC, AlexeyGvozdev commented on app/src/main/AndroidManifest.xml
> +            android:resource="@array/preloaded_fonts" />
А это зачем?

2022-04-29 10:16 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/MainActivity.java
> +    private Button series_btn, character_btn, quotes_btn, death_btn;
ты создал переменные на уровне всего класса, а используешь только в функции onCreate

2022-04-29 10:17 UTC, AlexeyGvozdev commented
Давай делать нормальные название коммитов и пулреквестов

2022-04-30 10:34 UTC, chandrey34 commented on app/build.gradle
> +    implementation 'androidx.navigation:navigation-fragment:2.3.5'
Это создала студия по умолчанию. По крайней мере я этот код не писал.

2022-04-30 10:35 UTC, chandrey34 commented on app/src/main/AndroidManifest.xml
> +            android:exported="false" />
Исправил на true, по умолчанию студия ставит false. Прочитал про действия exported.

2022-04-30 10:40 UTC, chandrey34 commented on app/src/main/AndroidManifest.xml
> +            android:resource="@array/preloaded_fonts" />
Студия добавила это по умолчанию. Я игрался с шрифтами в TextView в activity_series . По гуглил, это ставится по умолчанию как предварительная загрузка шрифтов.

2022-04-30 10:40 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/MainActivity.java
> +    private Button series_btn, character_btn, quotes_btn, death_btn;
Исправил

2022-04-30 10:40 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/MainActivity.java
> +        Intent intent = new Intent(this, SeriesActivity.class);
Исправил

2022-04-30 11:11 UTC, AlexeyGvozdev requested changes

2022-04-30 11:11 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/MainActivity.java
> +//        //обработчик события по нажатию на кнопку Серии
Удаляем закомментированный код. Нечего засорять классы

2022-04-30 11:11 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/MainActivity.java
> +        Intent intent = new Intent(this, SeriesActivity.class);
Ты не то сделал. Я просил объединить функции openSeriesActivity, openCharacterActivity, openQuotesActivity, openDeathActivity в одну, а ты сделал один обработчик кликов на кнопки. Верни как было и сделай как я прошу

2022-04-30 11:11 UTC, AlexeyGvozdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="150dp"
Только сейчас заметил, что у тебя слишком много захардкоженных значений в разетке. Это плохая практика. Попробуй сделать без указания ширины кнопке. Погугли про app:layout_constraintStart_toStartOf, app:layout_constraintLeft_toLeftOf, app:layout_constraintEnd_toEndOf и другие возможности ConstraintLayout

2022-04-30 11:11 UTC, AlexeyGvozdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="150dp"
Исправь только в activity_main, другие лейауты будем переделывать

2022-04-30 11:26 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/MainActivity.java
> +//        //обработчик события по нажатию на кнопку Серии
Оставил закомментированный код, т.к не был уверен что то исправляю, как раз сейчас раскомменчу и получится что верну как и было, ты как раз это просишь в другом комменте.

2022-04-30 14:49 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/MainActivity.java
> +        Intent intent = new Intent(this, SeriesActivity.class);
Исправил.

2022-04-30 21:22 UTC, chandrey34 commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="150dp"
Исправил. Ширину кнопки оставил, чтобы было красиво, т.к если делать по ширине текста, размер кнопки будет разный, а если делать по длине всего экрана то не получится того интерфейса что было запланировано.
Поигрался, изучил все возможности ConstraintLayout, изучил как работает Guidelines.

2022-05-01 07:06 UTC, AlexeyGvozdev requested changes

2022-05-01 07:06 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/MainActivity.java
> +    public void openActivity(View view) {
Лучше, но ещё не то, что нужно. Скажи, чем отличаются 57,58 строка от 61,62?

2022-05-01 07:06 UTC, AlexeyGvozdev commented on app/src/main/res/layout/activity_main.xml
> +        android:layout_width="150dp"
Хорошо, оставляем так

2022-05-02 18:26 UTC, AlexeyGvozdev requested changes

2022-05-02 18:26 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/MainActivity.java
> +    private void startActivity(Class<?> cls) {
Поменяй на `private void startActivity(Class<? extends AppCompatActivity> cls)`
иначе можно любой `Class` передать

2022-05-02 18:36 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/MainActivity.java
> +    private void startActivity(Class<?> cls) {
Исправил.

2022-05-02 18:41 UTC, merged