Добавил информацию о персонаже при клике на него
chandrey34/BreakingBadInfo pull request #4
Opened 2022-06-09 09:54 UTC by chandrey34

Что сделал:
*Создал активити CharacterInfoActivity
*Реализовал информацию о персонаже при клике на него

2022-06-09 09:56 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterAdapter.java
> +    public ArrayList<CharacterDataModel> characterList;
исправил на private

2022-06-09 16:26 UTC, AlexeyGvozdev requested changes

2022-06-09 16:26 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterDataList.java
> +        characterDataModel.add(new CharacterDataModel(R.drawable.character1, "Алексей Гвоздев", "Не помню(", "1,2,3", "Леха", "Алексей Гвоздев"));
Исправь на Лёха, через ё

2022-06-09 16:26 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoActivity.java
> +        int imageCharacterInfo = intent.getIntExtra("imageCharacterInfo", 0);
`"imageCharacterInfo"` в костанты

2022-06-10 08:16 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoActivity.java
> +        int imageCharacterInfo = intent.getIntExtra("imageCharacterInfo", 0);
исправил

2022-06-10 08:16 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterDataList.java
> +        characterDataModel.add(new CharacterDataModel(R.drawable.character1, "Алексей Гвоздев", "Не помню(", "1,2,3", "Леха", "Алексей Гвоздев"));
исправил)

2022-06-12 12:39 UTC, AlexeyGvozdev requested changes

2022-06-15 16:47 UTC, merged