Смена Activity на Fragment
chandrey34/BreakingBadInfo pull request #5
Opened 2022-06-20 19:04 UTC by chandrey34

Что сделал:
* Изменил activity на fragment
* удалил все активити кроме MainActivity
* передал данные из фрагмента в фрагмент (CharacterFragment/CharacterInfoFragment)

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterDataModel.java
> +    public CharacterDataModel() {
Это зачем?

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterFragment.java
> +        Bundle bundle = new Bundle();
Давай унесём это в `CharacterInfoFragment` фрагмент

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +        int imageCharacterInfo = characterDataModel.getCharacterImage();
лишние переменные можно сразу во вью устанавливать значения

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +        if (bundle != null) {
если null, то что будет?

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/DeathFragment.java
> +public class DeathFragment extends Fragment {
удали это. Добавишь когда будем делать экран смертей

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/MainFragment.java
> +public class MainFragment extends Fragment {
что такое MainFragment? может лучше HomeFragment?

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/MainFragment.java
> +                getActivity().getSupportFragmentManager().beginTransaction()
Те же грабли. Одинаковый код, что мы исправляли с интентом теперь пророс до одинакового кода с фрагментами

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/QuotesFragment.java
> +public class QuotesFragment extends Fragment {
Удаляй

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/res/layout/fragment_death.xml
> +<?xml version="1.0" encoding="utf-8"?>
удаляй

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/res/layout/fragment_main.xml
> +<?xml version="1.0" encoding="utf-8"?>
Переименовать файл

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/res/layout/fragment_quotes.xml
> +<?xml version="1.0" encoding="utf-8"?>
удаляй

2022-06-21 13:47 UTC, AlexeyGvozdev commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
удали

2022-06-22 18:31 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterFragment.java
> +        Bundle bundle = new Bundle();
сделал, спасибо за наводку)

2022-06-22 18:57 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +        int imageCharacterInfo = characterDataModel.getCharacterImage();
сначала не понял, а потом как понял, исправил

2022-06-22 19:11 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/MainFragment.java
> +public class MainFragment extends Fragment {
готово

2022-06-22 19:11 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/QuotesFragment.java
> +public class QuotesFragment extends Fragment {
готово

2022-06-22 19:12 UTC, chandrey34 commented on app/src/main/res/layout/fragment_main.xml
> +<?xml version="1.0" encoding="utf-8"?>
готово

2022-06-22 19:17 UTC, chandrey34 commented on app/src/main/res/values/strings.xml
> +    <string name="hello_blank_fragment">Hello blank fragment</string>
не понял вообще что это, но удалил 16, 17 строку

2022-06-23 20:10 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/MainFragment.java
> +                getActivity().getSupportFragmentManager().beginTransaction()
готово, оказалось легче чем я думал

2022-06-23 21:30 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +        if (bundle != null) {
хороший вопрос, на который я нашел следующий ответ:

>Этот аргумент Bundle будет доступен, даже если фрагмент каким-либо образом воссоздан Android, а это означает, что если он равен нулю, это связано с тем, что фрагмент, используемый для транзакции, не был создан с использованием вашего метода newInstance.
Поскольку этот случай происходит только в том случае, если разработчик неправильно использовал фрагмент, я обычно выбрасываю исключение IllegalArgumentException, чтобы сразу увидеть проблему.

таким образом, могу предположить что можно сделать вот так:
``` if (getArguments() != null) {
            characterDataModel = getArguments().getParcelable(CHARACTER_TAG);
        } else {
            throw new IllegalArgumentException();
        }
```
 опять же таки чтобы в случае чего увидеть свою ошибку,

2022-06-23 21:40 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +            characterDataModel = getArguments().getParcelable(CHARACTER_TAG);
тут корректнее будет наверное написать 
```
characterDataModel = bundle.getParcelable(CHARACTER_TAG);
```

2022-06-23 21:45 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterDataModel.java
> -    public CharacterDataModel() {
тут был твой вопрос "Зачем это?"
не вижу его сейчас, возможно случайно удалил.
Ответ: тупанул, не мог создать объект characterDataModel в CharacterInfoFragmet, добавил в CharacterInfoFragmet 
```
CharacterDataModel characterDataModel;
```
и все получилось.

2022-06-26 16:42 UTC, AlexeyGvozdev requested changes

2022-06-26 16:42 UTC, AlexeyGvozdev commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
это зачем?

2022-06-26 16:42 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +            characterDataModel = getArguments().getParcelable(CHARACTER_TAG);
да, сделай так

2022-06-26 16:42 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +            throw new IllegalArgumentException();
Это зачем? Ты же сам выкидываешь исключение

2022-06-26 16:42 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +    public static final String CHARACTER_TAG = "characterTag";
private

2022-06-26 16:42 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +    CharacterDataModel characterDataModel;
зачем вынесли в отдельное поле? Используем только в одной функции

2022-06-26 16:42 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/HomeFragment.java
> +                .replace(R.id.activity_main_container, fragment, tag)
что такое tag и зачем это нужно?

2022-06-27 17:35 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +    public static final String CHARACTER_TAG = "characterTag";
готово

2022-06-27 17:55 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/HomeFragment.java
> +                .replace(R.id.activity_main_container, fragment, tag)
я в некоторых ответах видел что пишут с тэгом, в некоторых что нет, если нажать ctrl и на .replase, то в документации написано 
```
public FragmentTransaction replace(@IdRes int containerViewId, @NonNull Fragment fragment,
            @Nullable String tag)
```

если честно так и не понял когда нужно использовать когда нет, щас убрал, сделал вот так
```
private void openFragment(Fragment fragment) {
        getActivity().getSupportFragmentManager().beginTransaction()
                .replace(R.id.activity_main_container, fragment)
                .addToBackStack(null)
                .commit();
    }
```

2022-06-27 17:55 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +            characterDataModel = getArguments().getParcelable(CHARACTER_TAG);
ок

2022-06-27 17:59 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +            throw new IllegalArgumentException();
ты мне задавал тут вопрос, если будет null, то что? Я подумал что нужно написать еще else, хотя нигде такого не видел, погуглил, нашел вот 

> Этот аргумент Bundle будет доступен, даже если фрагмент каким-либо образом воссоздан Android, а это означает, что если он равен нулю, это связано с тем, что фрагмент, используемый для транзакции, не был создан с использованием вашего метода newInstance.
Поскольку этот случай происходит только в том случае, если разработчик неправильно использовал фрагмент, я обычно выбрасываю исключение IllegalArgumentException, чтобы сразу увидеть проблему.

таким образом, могу предположить что можно сделать вот так:

            characterDataModel = getArguments().getParcelable(CHARACTER_TAG);
        } else {
            throw new IllegalArgumentException();
        }
опять же таки чтобы в случае чего увидеть свою ошибку, возможно что-то не так понял

2022-06-28 04:57 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +        if (bundle != null) {
я не это имел ввиду. Что у тебя будет на экране, если bundle == null?

2022-06-28 05:02 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +    CharacterDataModel characterDataModel;
ты поле используешь только в одной функции, как я вижу, а значит не стоит его на уровень класса выносить

2022-06-28 05:02 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/HomeFragment.java
> +                .replace(R.id.activity_main_container, fragment, tag)
плохо, что ты не разобрался. https://developer.android.com/guide/fragments/fragmentmanager

2022-06-28 17:14 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +    CharacterDataModel characterDataModel;
если правильно дошло, то сделал в методе ``` public View onCreateView() ```

2022-06-28 17:52 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +        if (bundle != null) {
если bundle == null, то ничего не будет, инфа о персонаже не откроется. приложение вылетит

2022-07-02 15:52 UTC, merged