Retrofit
chandrey34/BreakingBadInfo pull request #6
Opened 2022-07-11 20:05 UTC by chandrey34

Что сделал:
* Добавил название серий в список серий (моковые данные)
* Завел ретрофит

2022-07-13 18:11 UTC, AlexeyGvozdev requested changes

2022-07-13 18:11 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/BreakingBadApi.java
> +    @GET("episodes/")
Оставить один запрос

2022-07-13 18:11 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +import java.util.Scanner;
Удалить

2022-07-13 18:11 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +
удалить

2022-07-13 18:11 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/RetrofitClient.java
> +public class RetrofitClient {
Паттерн Синглтон

2022-07-13 18:11 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/SeasonDataList.java
> +        ArrayList<Series> season1 = new ArrayList<>();
Удалить

2022-07-13 18:11 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/Series.java
> +    @SerializedName(" title")
удали пустой символ

2022-07-13 18:13 UTC, AlexeyGvozdev requested changes

2022-07-13 18:26 UTC, AlexeyGvozdev commented
Создать `EpisodesApiResponse` его ты должен получать из запроса` getSeasonDataModel()`
Ты должен преобразовать `EpisodesApiResponse` в `SeasonDataModel`

2022-07-13 18:33 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/CharacterInfoFragment.java
> +import java.util.Scanner;
ок

2022-07-13 18:33 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/RetrofitClient.java
> +public class RetrofitClient {
ок

2022-07-13 18:34 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/Series.java
> +    @SerializedName(" title")
ок

2022-07-18 18:09 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/BreakingBadApi.java
> +    @GET("episodes/")
ок

2022-07-26 18:57 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/SeasonDataList.java
> +
пустую строку удалил, но как я понимаю, этот класс мне в принципе не нужен и надо его весь удалить, так?

2022-07-26 19:04 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/SeasonFragment.java
>          RetrofitClient.getRetrofitClient().getBreakingBadApi().getEpisodesApiResponse(getId()).enqueue(new Callback<List<EpisodesApiResponse>>() {
есть у меня большое предчувствие, что `getId()` тут не правильно

2022-08-22 05:40 UTC, AlexeyGvozdev requested changes

2022-08-22 05:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/SeasonDataMapper.java
> +//   SeasonDataMapper public static List<SeasonDataModel> transform(List<EpisodesApiResponse> episodesApiResponseList) {
удали закомментированный код

2022-08-22 05:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/SeasonDataMapper.java
> +    public static List<SeasonDataModel> transformSmart(List<EpisodesApiResponse> episodesApiResponseList) {
Блин, классно получилось! Молодец

2022-08-22 05:40 UTC, AlexeyGvozdev commented on app/src/main/java/com/example/breakingbadinfo/SeasonDataModel.java
> +//    @Override
удаляем

2022-08-22 20:30 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/SeasonDataMapper.java
> +//   SeasonDataMapper public static List<SeasonDataModel> transform(List<EpisodesApiResponse> episodesApiResponseList) {
ок

2022-08-22 20:30 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/SeasonDataMapper.java
> +    public static List<SeasonDataModel> transformSmart(List<EpisodesApiResponse> episodesApiResponseList) {
я старался, спасибо)

2022-08-22 20:32 UTC, chandrey34 commented on app/src/main/java/com/example/breakingbadinfo/SeasonDataModel.java
> +//    @Override
ок

2022-08-22 20:33 UTC, merged